const Images = {
  DoubleEagleBanner: require('../assets/images/double-eagle-image.jpeg'),
  DoubleEagleLogo: require('../assets/images/double-eagle-logo.png'),
  GolfClubNewAlbanyBanner: require('../assets/images/The-Golf-Club-New-Albany-image.jpeg'),
  GolfClubNewAlbanyLogo: require('../assets/images/The-Golf-Club-New-Albany-logo.png'),
  LakesGolfBanner: require('../assets/images/The-Lakes-Golf-and-Country-Club-image.jpeg'),
  LakesGolfLogo: require('../assets/images/The-Lakes-Golf-and-Country-Club-logo.png'),
  MuirfieldBanner: require('../assets/images/The-Muirfield-Village-Golf-and-Country-Club-image.jpeg'),
  MuirfieldLogo: require('../assets/images/Murfield-Village.jpeg'),
  MedallionBanner: require('../assets/images/Medallion-image.jpeg'),
  MedallionLogo: require('../assets/images/Medallion-logo.png'),
  JeffersonBanner: require('../assets/images/Jefferson-Country-Club-image.jpeg'),
  JeffersonLogo: require('../assets/images/Jefferson-Country-Club-logo.png'),
  NewAlbanyBanner: require('../assets/images/New-Albany-Country-Club-image.jpeg'),
  NewAlbanyLogo: require('../assets/images/New-Albany-Country-Club-logo.jpeg'),
  DunesCourseBanner: require('../assets/images/bandon-dunes.jpeg'),
  DunesCourseLogo: require('../assets/images/bandon-dunes-logo.png'),
  BandonPreserveBanner: require('../assets/images/bandon-preserve.jpeg'),
  BandonPreserveLogo: require('../assets/images/bandon-preserve-logo.png'),
  BandonTrailsBanner: require('../assets/images/bandon-trails.jpeg'),
  BandonTrailsLogo: require('../assets/images/brandon-trails-logo.png'),
  PacificDunesBanner: require('../assets/images/pacific-dunes.jpeg'),
  PacificDunesLogo: require('../assets/images/pacific-dunes-logo.png'),
  OldMacdonaldBanner: require('../assets/images/old-macdonald.jpeg'),
  OldMacdonaldLogo: require('../assets/images/Old-Macdonald-logo.png'),
  PracticeCenterBanner: require('../assets/images/practice-center-shortys.jpeg'),
  PracticeCenterLogo: require('../assets/images/practice-center-shortys-logo.png'),
  PunchbowlBanner: require('../assets/images/punchbowl.jpeg'),
  PunchbowlLogo: require('../assets/images/punchbowl-logo.png'),
  SheepRanchBanner: require('../assets/images/sheep-ranch.jpeg'),
  SheepRanchLogo: require('../assets/images/sheep-ranch-logo.png'),
  ProfileIntro1: require('../assets/images/profile-intro-1.jpeg'),
  ProfileIntro2: require('../assets/images/profile-intro-2.jpeg'),
  ProfileIntro3: require('../assets/images/profile-intro-3.jpeg'),
  ProfileIntro4: require('../assets/images/profile-intro-4.jpeg'),
  ProfileIntro5: require('../assets/images/profile-intro-5.jpeg'),
  imgLogin01: require('../assets/images/imgLogin01.png'),
  imgLogin02: require('../assets/images/imgLogin02.png'),
  imgLogin03: require('../assets/images/imgLogin03.png'),
}

export default Images
